name: CI
on: push
jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v3
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install poetry
        uses: snok/install-poetry@v1
      - name: install
        run: |
          poetry install
      - name: Install linting tools
        run: |
          python -m pip install mypy flake8 pylint
      - name: run lint
        run: |
          make lint
  format:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v3
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install poetry
        uses: snok/install-poetry@v1
      - name: install
        run: |
          poetry install
      - name: run format
        run: |
          make format-check
